### ISSUE TITLE
Error on calc all map (lines)

### ISSUE THREAD

**Issue by Micka41** [EinEinfach/CaSSAndRA#2]
Hello,

When I try to calculate the mowing map with pattern lines, I have a round hourglass that appears and after several minutes, nothing and the map is not calculated.

The width is 0.14
The angle is 115°
[map.txt](https://github.com/EinEinfach/CaSSAndRA/files/11684404/map.txt)

` File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.10/dist-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/root/CaSSAndRA/CaSSAndRA/src/components/state/map.py", line 55, in update
    path.calc(mapdata.mowoffsetstatepage, mapdata.mowanglestatepage, rover_position, mapdata.patternstatepage)
  File "/root/CaSSAndRA/CaSSAndRA/src/backend/map/path.py", line 20, in calc
    route = lines.calcroute(area_to_mow, border, line_mask, edge_polygons, route)
  File "/root/CaSSAndRA/CaSSAndRA/src/backend/map/lines.py", line 539, in calcroute
    possible_way = LineString([route[-1], perimeter_coords[start_coords_nr]])
IndexError: list index out of range`

PS: The application is wonderfull  !

**Comment by EinEinfach** [comment]
Hello Micka, your map looks like a worst case for my path planner :) I will rewrite path planner soon to increase performance. I hope it will solve this problem. Anyway I have know one test case

**Comment by Micka41** [comment]
Thanks, I'm looking forward to the rewrite!

**Comment by EinEinfach** [comment]
Looks good now also with old planer

**Comment by Micka41** [comment]
Hello

I still have the problem

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/dist-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.10/dist-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/root/CaSSAndRA/CaSSAndRA/src/components/state/map.py", line 55, in update
    path.calc(mapdata.mowoffsetstatepage, mapdata.mowanglestatepage, rover_position, mapdata.patternstatepage)
  File "/root/CaSSAndRA/CaSSAndRA/src/backend/map/path.py", line 20, in calc
    route = lines.calcroute(area_to_mow, border, line_mask, edge_polygons, route)
  File "/root/CaSSAndRA/CaSSAndRA/src/backend/map/lines.py", line 539, in calcroute
    possible_way = LineString([route[-1], perimeter_coords[start_coords_nr]])
IndexError: list index out of range`

**Comment by EinEinfach** [comment]
Can you attach beginning of the log (the moment where you click for way calculation)

**Comment by EinEinfach** [comment]
Hello Micka,
now it should be fine. The path planner work properly
Cheers
Alexander

**Comment by Micka41** [comment]
It's works 
Thanks you !!
