### ISSUE TITLE
Cassandra crashes after reconnect in http unencrypted mode

### ISSUE THREAD

**Issue by EinEinfach** [EinEinfach/CaSSAndRA#24]
2023-07-21 17:08:06 WARNING Backend: Http request for props delivered implausible string
2023-07-21 17:08:07 INFO Backend: Try initial HTTP request
2023-07-21 17:08:07 DEBUG Calced checksumme: 0x16
2023-07-21 17:08:07 DEBUG Data to be send: AT+V,0x16
2023-07-21 17:08:07 DEBUG Starting new HTTP connection (1): 192.168.0.139:80
023-07-21 17:08:08 DEBUG http://192.168.0.139:80 "POST / HTTP/1.1" 200 321
2023-07-21 17:08:08 DEBUG Status code: 200
2023-07-21 17:08:08 DEBUG Content: S,24.50,-30.59,37.12,-3.14,2,1,14,17.72,11,-30.73,37.49,0.02,30,0.92,29,-340085,0.14,0x23
T,2827,0,12899,614,11552,15,2802.27,23.04,0,27.26,54.83,14,0,0.03,1024,733,91,8,198239,1,48,0,0,0,81,0x6c
V,Sunray,1.0.306,0,0,Adafruit Grand Central M4,AM,XX,XX,d7:a6:4c:c3:53:50:53:38:4a:20:20M4,AM,XX,XAM,XX,XX,dXX,XX,d7:XX,d7: 
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/lib/python3.9/threading.py", line 892, in run
self._target(*self._args, **self._kwargs)
File "/home/ardumower/CaSSAndRA/CaSSAndRA/src/backend/backendserver.py", line 28, in connect_http
connection = httpcomm.connect_http(connect_data)
File "/home/ardumower/CaSSAndRA/CaSSAndRA/src/backend/comm/httpcomm.py", line 86, in connect_http
encrypt = int(reslist[3])
ValueError: invalid literal for int() with base 10: '37.12'

**Comment by EinEinfach** [comment]
AT+S and other cmds have to be stopped before reconnect and AT+V cmd end successfully

**Comment by disaster123** [comment]
does this need any fix in sunray? May be I can provide a fix - but currently i'm unsure what the issue is.

**Comment by EinEinfach** [comment]
Can't investigate at the moment. I'm on trip at the moment. But what I saw in the posted logs in forum, there are all three answers (AT+S, AT+T and AT+V) in one http response. I have no idea how could it happened. I can provide some tests in Cassandra before consuming the response, it will be fix the problem, but the question will be remained unanswered

**Comment by disaster123** [comment]
which hardware? Alfred has for example a different implementation than the original arduino stuff.

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/7ef713d53e1d31c80eeeaba2a64caef78ea4e56f
