### ISSUE TITLE
float value to int conversion errror

### ISSUE THREAD

**Issue by AndiTheBest** [EinEinfach/CaSSAndRA#34]
Hi. The Backend died on this:
Should be easy to fix.

2023-08-08 15:38:48 DEBUG Recieved checksum:0x32 Calced checksum: 0x32
2023-08-08 15:38:48 DEBUG Backend: Calc data from stats data frame
2023-08-08 15:38:48 INFO Backend: Performing get state http-request
2023-08-08 15:38:48 DEBUG Calced checksumme: 0x13
2023-08-08 15:38:48 DEBUG Encryption: true
2023-08-08 15:38:48 DEBUG Data to be send: M`7_8<%=?
2023-08-08 15:38:48 DEBUG Starting new HTTP connection (1): 10.0.0.60:80
2023-08-08 15:38:50 DEBUG http://10.0.0.60:80 "POST / HTTP/1.1" 200 0
2023-08-08 15:38:50 DEBUG Status code: 200
2023-08-08 15:38:50 DEBUG Content:
2023-08-08 15:38:50 WARNING Backend: HTTP request for state delivered implausible string
2023-08-08 15:38:50 INFO Backend: Try initial HTTP request
2023-08-08 15:38:50 DEBUG Calced checksumme: 0x16
2023-08-08 15:38:50 DEBUG Data to be send: AT+V,0x16
2023-08-08 15:38:50 DEBUG Starting new HTTP connection (1): 10.0.0.60:80
2023-08-08 15:38:51 DEBUG http://10.0.0.60:80 "POST / HTTP/1.1" 200 185
2023-08-08 15:38:51 DEBUG Status code: 200
2023-08-08 15:38:51 DEBUG Content: S,24.27,-1.34,6.77,-1.11,1,1,1764,4.98,9,-1.23,6.50,0.04,38,0.34,27,-294138,0.00,0x6a
V,Sunray,1.0.305,1,162,Arduino Due,AM,XX,XX,51:20:31:20:38:32:54:50:31:30:33:32:32:31:30:35,0x39

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/cassandra/CaSSAndRA/CaSSAndRA/src/backend/backendserver.py", line 28, in connect_http
    connection = httpcomm.connect_http(connect_data)
  File "/home/pi/cassandra/CaSSAndRA/CaSSAndRA/src/backend/comm/httpcomm.py", line 86, in connect_http
    encrypt = int(reslist[3])
ValueError: invalid literal for int() with base 10: '6.77'

**Comment by EinEinfach** [comment]
It's on to do list
[](https://github.com/EinEinfach/CaSSAndRA/issues/24)

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/commit/7ef713d53e1d31c80eeeaba2a64caef78ea4e56f
