### ISSUE TITLE
ValueError: mutable default <class 'pandas.core.frame.DataFrame'> for field last_cmd is not allowed: use default_factory

### ISSUE THREAD

**Issue by Micka41** [EinEinfach/CaSSAndRA#6]
Hi,

In Python 3.11, I get this error (in aarch64 and amd64) :
(cassandra.app) pi@tondeuse:~/cassandra.app/CaSSAndRA/CaSSAndRA $ python3.11 app.py 
2023-07-04 17:01:05 DEBUG Backend: rovercfg to read: {'mowspeed_setpoint': 0.25, 'gotospeed_setpoint': 0.3, 'positionmode': 'relative', 'lon': 0, 'lat': 0}
2023-07-04 17:01:05 DEBUG Backend: pahtplannercfg to read: {'pattern': 'lines', 'width': 0.18, 'angle': 0, 'distancetoborder': 2, 'mowarea': 'yes', 'mowborder': 0, 'mowexclusion': 'yes', 'mowborderccw': 'yes'}
2023-07-04 17:01:05 DEBUG Backend: pahtplannercfg to read: {'pattern': 'lines', 'width': 0.18, 'angle': 0, 'distancetoborder': 2, 'mowarea': 'yes', 'mowborder': 0, 'mowexclusion': 'yes', 'mowborderccw': 'yes'}
2023-07-04 17:01:05 DEBUG Backend: appcfg to read: {'datamaxage': 30, 'time_to_offline': 30, 'voltage_to_soc': [{'V': 22, 'SoC': 0}, {'V': 28, 'SoC': 100}], 'current_thd_charge': -0.03, 'rover_picture': 'ardumower/'}
Traceback (most recent call last):
  File "/home/pi/cassandra.app/CaSSAndRA/CaSSAndRA/app.py", line 25, in <module>
    from src.components import ids, navbar, offcanvas, modalremotecontrol, modalinfo
  File "/home/pi/cassandra.app/CaSSAndRA/CaSSAndRA/src/components/offcanvas.py", line 7, in <module>
    from . import joystick, ids
  File "/home/pi/cassandra.app/CaSSAndRA/CaSSAndRA/src/components/joystick.py", line 7, in <module>
    from src.backend.data.roverdata import robot
  File "/home/pi/cassandra.app/CaSSAndRA/CaSSAndRA/src/backend/data/roverdata.py", line 15, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'pandas.core.frame.DataFrame'> for field last_cmd is not allowed: use default_factory

**Comment by Micka41** [comment]
No problem with Python 3.10, but I can't switch to this version

**Comment by EinEinfach** [comment]
I know, already known.

Seems to be a python problem. Look here:

https://github.com/huggingface/datasets/issues/5230

**Comment by Micka41** [comment]
Aaaahhh. 
I spent 2 days installing Python 3.11 on a nice Buster after migrating from Stretch.
Well, I'm trying to install Python 3.10 :'(

**Comment by vijayroykargwal** [comment]
Any update on this one for python 3.11 or above

**Comment by EinEinfach** [comment]
Not yet, but I think it will be easy to fix. All pd.DataFrames definitions in dataclasses have to be replaced by default_factory

**Comment by EinEinfach** [comment]
https://github.com/EinEinfach/CaSSAndRA/pull/106
