### ISSUE TITLE
Error in Latest Updates for MQTT Client

### ISSUE THREAD

**Issue by rothnic** [EinEinfach/CaSSAndRA#80]
Just tried running the latest commit via docker container and I'm seeing a new error that must have come from the connection refactor.

```
2023-09-29 13:55:57 WARNING Backend: Could not connect to the rover. State set to offline
Exception in thread Thread-2 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1558, in loop_read
    return self._loop_rc_handle(rc)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2350, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3475, in _do_on_disconnect
    on_disconnect(self, self._userdata, rc)
TypeError: MQTT.on_disconnect() missing 1 required positional argument: 'rc'
```

**Comment by EinEinfach** [comment]
I don't understand "why" at the moment... because RC flag is given to on_disconnect function. It must be something others. But connection goes well?

**Comment by rothnic** [comment]
> I don't understand "why" at the moment... because RC flag is given to on_disconnect function. It must be something others. But connection goes well?

I think I see why. Looking back at the original version, the signature of the method is different.

It should be `def on_disconnect(client, userdata, rc):` , not `def on_disconnect(self, client, userdata, flags, rc):`. See [here](https://github.com/EinEinfach/CaSSAndRA/blob/master/CaSSAndRA/src/backend/comm/connections.py#L68C5-L68C58)

**Comment by EinEinfach** [comment]
Try that, but actually within the data class, the class itself must be passed first.

**Comment by rothnic** [comment]
> Try that, but actually within the data class, the class itself must be passed first.
> 
> on_connect function works well

It isn't the `self` that is the issue I'm pointing out. The `on_connect` and `on_disconnect` callbacks have different signatures. The `on_disconnect` shouldn't have `flags`.

**Comment by EinEinfach** [comment]
I think I see the problem:

def on_disconnect(self, client, userdata, flags, rc): 

have to be replaced by:

def on_disconnect(self, client, userdata, rc):

**Comment by rothnic** [comment]
> def on_disconnect(self, client, userdata, flags, rc):
> 
> have to be replaced by:
> 
> def on_disconnect(self, client, userdata, rc):

Yeah, that is the issue. For some reason they just have slightly different signatures between on_connect and on_disconnect

**Comment by EinEinfach** [comment]
Did you see more disconnecting issues? Can we close this issue?

**Comment by EinEinfach** [comment]
Does it work now? Can we close this issue?
