### ISSUE TITLE
One task temporarily shown on state page

### ISSUE THREAD

**Issue by rothnic** [EinEinfach/CaSSAndRA#88]
Just trying the latest changes here `eineinfach/cassandra:sha-3ba1625`. I used the open to select about 6 tasks from the main state page to execute in order. There is a loading progress screen you see, then the progress bar goes away, and for about 20 seconds or so I saw only the paths for one of the tasks. After about 20 seconds or so, it updated and showed the paths for all the tasks, but it was confusing until that happened.

**Comment by ShadedSelf** [comment]
I kinda thought this was just my slow Pi2 and/or slow network, callbacks piling up, takes a while for dash to catch up and show the current state, could be something else though.

**Comment by rothnic** [comment]
It might be something related to the errors I saw in my log file:

```
2023-10-07 11:01:00 INFO Backend: Turning shapely figure: Point Angle: 0
2023-10-07 11:01:00 INFO Backend: Turning shapely figure: Polygon Angle: 0
2023-10-07 11:01:00 INFO Backend: Create map borders and area to mow
2023-10-07 11:01:00 INFO Backend: Calc route for cutedge
2023-10-07 11:01:00 INFO Coverage path planner (planing route for cut to edge): Calculation finished
2023-10-07 11:01:00 INFO Backend: Create line mask
2023-10-07 11:01:00 INFO Coverage path planner (lines): Start coverage path planner
2023-10-07 11:01:00 INFO Coverage path planner (calc lines): Starting loop
2023-10-07 11:01:01 ERROR Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/cassandra/app/src/layout.py", line 64, in update_progress_bar
    data[current_map.task_progress]["props"]["value"] = max(data[task]["props"]["value"], progress)
IndexError: list index out of range
2023-10-07 11:01:02 INFO Coverage path planner (calc lines): No more way to calculate, ending loop
2023-10-07 11:01:02 INFO Backend: Turning shapely figure: LineString Angle: 0
2023-10-07 11:01:02 ERROR Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/cassandra/app/src/layout.py", line 64, in update_progress_bar
    data[current_map.task_progress]["props"]["value"] = max(data[task]["props"]["value"], progress)
IndexError: list index out of range
2023-10-07 11:01:02 INFO Backend: Check for selection and create a new perimter if there
2023-10-07 11:01:02 INFO Backend: Selection lasso detected. Create a new perimeter with lasso select.
2023-10-07 11:01:02 INFO Backend: Planning route:
2023-10-07 11:01:02 INFO PathPlannerCfg(pattern='lines', width=0.16, angle=45, distancetoborder=2, mowarea=True, mowborder=2, mowexclusion=True, mowborderccw=True)
2023-10-07 11:01:02 INFO Rover start position: (20.46641503725019, -1.8211247247286106)
2023-10-07 11:01:02 INFO Backend: Turning shapely figure: Point Angle: -45
2023-10-07 11:01:02 INFO Backend: Turning shapely figure: Polygon Angle: -45
2023-10-07 11:01:02 INFO Backend: Create map borders and area to mow
2023-10-07 11:01:02 INFO Backend: Calc route for cutedge
2023-10-07 11:01:02 INFO Coverage path planner (planing route for cut to edge): Calculation finished
2023-10-07 11:01:02 INFO Backend: Create line mask
2023-10-07 11:01:02 INFO Coverage path planner (lines): Start coverage path planner
2023-10-07 11:01:03 INFO Coverage path planner (calc lines): Starting loop
2023-10-07 11:01:03 ERROR Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/usr/local/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/cassandra/app/src/layout.py", line 64, in update_progress_bar
    data[current_map.task_progress]["props"]["value"] = max(data[task]["props"]["value"], progress)
IndexError: list index out of range
```

**Comment by ShadedSelf** [comment]
I see, do you have more than 6 tasks?

I was waiting for @EinEinfach to tell me wether to keep the color bars or not to properly fix it all up. The above should not happen anyways, I forgot to clamp that index.

**Comment by EinEinfach** [comment]
Ok, I didn’t check that you waiting. I prefer the progress bar color related to the task color.
